# vim: noexpandtab:ts=4:sw=4

provider = coldrye
os = debian
release = testing
feature = bind
feature_version = 9.10.3
tag := $(shell date +"%Y%m%d%H%M%S")
image = $(os)-$(feature)

include ../../Makefile.in

